// Generate docs/i18n-terms.md from the live I18N catalog in index.html, so the
// review doc never drifts from the code. Run from the repo root:
//   node app/ui/i18n-terms.mjs
import { readFileSync, writeFileSync } from "node:fs";

const html = readFileSync("app/ui/index.html", "utf8");
// The catalog is a plain object literal `var I18N = { en: {...}, zh: {...} };`
// terminated by a column-0 `};` — grab it and eval (our own committed literal).
const m = html.match(/var I18N = (\{[\s\S]*?\n\});/);
if (!m) { console.error("I18N catalog not found in index.html"); process.exit(1); }
const I18N = (0, eval)("(" + m[1] + ")"); // eslint-disable-line no-eval

const keys = Object.keys(I18N.en);
const groups = {};
for (const k of keys) { const g = k.includes(".") ? k.split(".")[0] : "misc"; (groups[g] = groups[g] || []).push(k); }

let md = "# Kwire UI terms — English → 中文 (Simplified, zh-Hans)\n\n";
md += "Review the **中文** column and tell me any wording you'd refine; I'll update the\n";
md += "catalog in `app/ui/index.html`. Book titles/authors are never translated — this is\n";
md += "app chrome only. Auto-generated by `app/ui/i18n-terms.mjs` (do not hand-edit).\n\n";
md += `Total terms: **${keys.length}**.\n`;
for (const g of Object.keys(groups).sort()) {
  md += `\n## ${g}\n\n| Key | English | 中文 |\n|---|---|---|\n`;
  for (const k of groups[g].sort()) {
    const en = String(I18N.en[k]).replace(/\|/g, "\\|");
    const zh = I18N.zh[k] == null ? "⚠️ MISSING" : String(I18N.zh[k]).replace(/\|/g, "\\|");
    md += `| \`${k}\` | ${en} | ${zh} |\n`;
  }
}
writeFileSync("docs/i18n-terms.md", md);
console.log(`wrote docs/i18n-terms.md — ${keys.length} terms across ${Object.keys(groups).length} groups`);
